export const data=[
    {
		id: 1,
		img: '/src/assets/1.jpg',
		nameProduct: 'Meishen te',
		price: 30000,
		quantity: 1,
	},
	{
		id: 2,
		img:'/src/assets/2.jpg',
		nameProduct: 'Te forma',
		price: 45000,
		quantity: 1,
	},
	{
		id: 3,
		img: '/src/assets/3.jpg',
		nameProduct: 'Te relaxnat',
		price: 65000,
		quantity: 1,
	},
	{
		id: 4,
		img: '/src/assets/4.jpg',
		nameProduct: 'Biotina con colageno',
		price: 55000,
		quantity: 1,
	},
	{
		id: 5,
		img: '/src/assets/5.jpg',
		nameProduct:'Purecell',
		price: 20000,
		quantity: 1,
	},
	{
		id: 6,
		img: '/src/assets/6.jpg',
		nameProduct: 'Enscia ansioff',
		price: 30000,
		quantity: 1,
	}, 
	{
		id: 7,
		img: '/src/assets/7.jpg',
		nameProduct: 'Meishen concentrado',
		price: 40000,
		quantity: 1,
	}, 
	{
		id: 8,
		img: '/src/assets/8.jpg',
		nameProduct: 'Levadura de cerveza',
		price: 45000,
		quantity: 1,
	}, 
	{
		id: 9,
		img: '/src/assets/9.jpg',
		nameProduct: 'Garcinia',
		price: 60000,
		quantity: 1,
	},
	{
		id: 10,
		img: '/src/assets/10.jpg',
		nameProduct: 'Echinacea',
		price: 75000,
		quantity: 1,
	}, 
	{
		id: 11,
		img: '/src/assets/11.jpg',
		nameProduct: 'vitacer + guarana',
		price: 75000,
		quantity: 1,
	}, 
	{
		id: 12,
		img: '/src/assets/12.jpg',
		nameProduct: 'vitacer',
		price: 45000,
		quantity: 1,
	}, 
]